FROM node:20-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-workspace.yaml ./
COPY backend/package.json ./backend/package.json
COPY packages/shared/package.json ./packages/shared/package.json

RUN pnpm install --frozen-lockfile=false

COPY packages/shared ./packages/shared
COPY backend ./backend

WORKDIR /app/backend

RUN pnpm exec prisma generate

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]
