export enum CampaignStatus {
  DRAFT_TARGETING = "DRAFT_TARGETING",
  TARGETING_SET = "TARGETING_SET",
  SCRAPING = "SCRAPING",
  SCRAPED = "SCRAPED",
  DRAFT_MESSAGING = "DRAFT_MESSAGING",
  READY = "READY",
  RUNNING = "RUNNING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum CampaignContactStatus {
  PENDING = "PENDING",
  MESSAGE_SENT = "MESSAGE_SENT",
  REPLIED = "REPLIED",
  INTERESTED = "INTERESTED",
  MEETING_BOOKED = "MEETING_BOOKED",
  NOT_INTERESTED = "NOT_INTERESTED",
  FAILED = "FAILED",
}

export enum ScrapingJobStage {
  COMPANY_SEARCH = "COMPANY_SEARCH",
  DECISION_MAKER_SEARCH = "DECISION_MAKER_SEARCH",
}

export enum ScrapingJobStatus {
  QUEUED = "QUEUED",
  RUNNING = "RUNNING",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
}

export enum CampaignChannel {
  LINKEDIN = "LINKEDIN",
}

export enum UnipileAccountStatus {
  CONNECTED = "CONNECTED",
  DISCONNECTED = "DISCONNECTED",
  ERROR = "ERROR",
}
