export enum UnipileAccountStatus {
  CONNECTED = "CONNECTED",
  DISCONNECTED = "DISCONNECTED",
  ERROR = "ERROR",
}

export enum ProspectListStatus {
  DRAFT = "DRAFT",
  BRIEF_SET = "BRIEF_SET",
  SCRAPING = "SCRAPING",
  ENRICHING = "ENRICHING",
  READY = "READY",
  FAILED = "FAILED",
}

export enum ScrapingRunStage {
  COMPANY_SEARCH = "COMPANY_SEARCH",
  PROSPECT_ENRICHMENT = "PROSPECT_ENRICHMENT",
}

export enum ScrapingRunStatus {
  QUEUED = "QUEUED",
  RUNNING = "RUNNING",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
}

export enum ProspectStatus {
  PENDING = "PENDING",
  MESSAGE_SENT = "MESSAGE_SENT",
  REPLIED = "REPLIED",
  INTERESTED = "INTERESTED",
  MEETING_BOOKED = "MEETING_BOOKED",
  NOT_INTERESTED = "NOT_INTERESTED",
  FAILED = "FAILED",
}
